"""create movie comments table

Revision ID: 11a79ae9465f
Revises: 1d7611cb8619
Create Date: 2026-02-03 08:55:39.563070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11a79ae9465f'
down_revision: Union[str, Sequence[str], None] = '1d7611cb8619'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie_comments', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'fk_movie_comments_parent_id',
        'movie_comments',
        'movie_comments',
        ['parent_id'],
        ['id'],
        ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fk_movie_comments_parent_id',  # То же имя что в upgrade
        'movie_comments',
        type_='foreignkey'
    )
    op.drop_column('movie_comments', 'parent_id')
    # ### end Alembic commands ###
