"""create movie comments table

Revision ID: 1d7611cb8619
Revises: 367d8605c8ff
Create Date: 2026-02-03 08:52:10.348073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d7611cb8619'
down_revision: Union[str, Sequence[str], None] = '367d8605c8ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('movie_comments_parent_id_fkey'), 'movie_comments', type_='foreignkey')
    op.drop_column('movie_comments', 'parent_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie_comments', sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('movie_comments_parent_id_fkey'), 'movie_comments', 'movie_comments', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
