"""improve order constraints

Revision ID: 35e1628f2881
Revises: 248998c2c3ab
Create Date: 2026-03-01 15:08:03.549330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35e1628f2881'
down_revision: Union[str, Sequence[str], None] = '248998c2c3ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_order_movie'), 'order_items', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_order_movie'), 'order_items', ['order_id', 'movie_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
